name: $(Build.SourceBranchName).$(date:yyyyMMdd)$(rev:.r) 

variables:
  Project.Name: bc_golden_plugin
  Project.Directory: $(System.DefaultWorkingDirectory)/$(Project.Name)
  Project.version: 1.2.0
resources:
  - repo: self

trigger:
  branches:
    include:
      - trunk
      - feature/*
  paths:
    include:
      - bc_golden_plugin/*

stages:
  - stage: Build
    jobs:
    - job: BuildJob
      pool:
        vmImage: 'macOS-11'
      steps:
      - template: ../pipelines/config.yaml
      - template: ../pipelines/publish.yaml