name: bc_golden_lint
description: >
  analysis_server_plugin providing an IDE quick assist to convert
  BcGoldenCapture.multiple(...) calls into independent BcGoldenCapture.single tests.
version: 0.1.0
repository: https://github.com/bancolombia/bc_golden_plugin

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  analysis_server_plugin: ">=0.3.3 <0.4.0"
  analyzer: ">=14.0.0 <15.0.0"
  analyzer_plugin: ">=0.13.10 <1.0.0"
dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.1
